USE CoMuteV2
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users')
	BEGIN
		DROP TABLE Users
	END
ELSE
	BEGIN
		CREATE TABLE Users(
			UserID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
			Name VARCHAR(50) NOT NULL,
			Surname VARCHAR(50) NOT NULL,
			Phone VARCHAR(50),
			Email VARCHAR(50) NOT NULL,
			Password VARBINARY(MAX) NOT NULL
		)
	END
GO


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Owner')
	BEGIN
		DROP TABLE Owner
	END
ELSE
	BEGIN
		CREATE TABLE Owner(
			OwnerID INT IDENTITY(1, 1) PRIMARY KEY FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
			Salt VARBINARY(MAX) NOT NULL
		)
	END
GO


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CarPoolTicketStatus')
	BEGIN
		DROP TABLE CarPoolTicketStatus
	END
ELSE
	BEGIN
		CREATE TABLE CarPoolTicketStatus(
			CarPoolTicketStatusID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
			Status VARCHAR(50)
		)
	END
GO


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PassengerStatus')
	BEGIN
		DROP TABLE PassengerStatus
	END
ELSE
	BEGIN
		CREATE TABLE PassengerStatus(
			PassengerStatusID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
			PassengerStatus VARCHAR(50)
		)
	END
GO


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CarPoolTicket')
	BEGIN
		DROP TABLE CarPoolTicket
	END
ELSE
	BEGIN
		CREATE TABLE CarPoolTicket(
			CarPoolTicketID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,			
			OwnerID INT FOREIGN KEY REFERENCES Owner(OwnerID),
			CarPoolTicketStatusID INT REFERENCES CarPoolTicketStatus(CarPoolTicketStatusID),
			Origin VARCHAR(500) NOT NULL, 
			Destination VARCHAR(500) NOT NULL,
			DepartureTime DATETIME NOT NULL,
			ExpectedArrivalTime DATETIME NOT NULL,
			AvailableSeats INT,
			Note VARCHAR(800),
			CreatedDate DATETIME
		)
	END
GO



IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CarPoolTicketAllocation')
	BEGIN
		DROP TABLE CarPoolTicketAllocation
	END
ELSE
	BEGIN
		CREATE TABLE CarPoolTicketAllocation(
			CarPoolTicketAllocationID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
			CarPoolTicketID INT FOREIGN KEY REFERENCES CarPoolTicket(CarPoolTicketID),
			PassengerID INT FOREIGN KEY REFERENCES Owner(OwnerID),
			PassengerNote VARCHAR(800),
			PassengerRegisterDate DATETIME,
			PassengerStatusID INT FOREIGN KEY REFERENCES PassengerStatus(PassengerStatusID)
		)
	END
GO